name: conda1
channels:
  - r
  - bioconda
  - conda-forge
dependencies:
  - r-base=4.4.0
  - r-tidyverse
  - r-ggplot2
  - bioconductor-deseq2
  - r-seurat>=5
  - r-leiden
  - r-reticulate
  - r-glue
  - r-sessioninfo
  - python>=3.9
  - pip
  - pip:
      - numpy
      - pandas
      - python-igraph
      - leidenalg
